### ISSUE TITLE
Patch failing rather than saying that the file is missing

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/wildfly#101]
##### SUMMARY

If the patch version mentioned in the playbook is not available, the playbooks fails with a cryptic error. We should add an assert checking that the patch file can be found.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
# ansible --version
ansible [core 2.12.6]
  config file = /work/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.8/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.8.12 (default, Sep 16 2021, 10:46:05) [GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
  jinja version = 2.10.3
  libyaml = True

```

##### COLLECTION VERSION

```
# ansible-galaxy collection list

# /root/.ansible/collections/ansible_collections
Collection                 Version
-------------------------- -------
redhat.eap                 1.3.1  
redhat.redhat_csp_download 1.2.2
```

##### STEPS TO REPRODUCE

```yaml
---
- name: Converge
  hosts: all
  vars:
    eap_offline_install: True
    eap_apply_cp: True
    eap_patch_version: 7.4.9
  collections:
    - redhat.eap
  roles:
    - eap_install
    - eap_systemd
  post_tasks:
    - ansible.builtin.service:
        name: eap
        state: restarted
```

##### EXPECTED RESULTS

Assert fails and state that the path to the patch file is invalid.

##### ACTUAL RESULTS

TASK [redhat.eap.eap_utils : Set checksum file path for patch] ********************************
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'checksum'\n\nThe error appears to be in '/root/.ansible/collections/ansible_collections/redhat/eap/roles/eap_utils/tasks/apply_cp.yml': line 85, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: \"Set checksum file path for patch\"\n  ^ here\n"}

```

```
