### ISSUE TITLE
YAML Configuration question

### ISSUE THREAD

**Issue by fbartusch** [ansible-middleware/wildfly#132]
Hi,

I'm configuring wildfly with the new YAML configuration method. The configuration itself works perfectly for me, but I have a question regarding file organization on my ansible controller and if the behavior I describe is intended.

In my directory structure, the playbook `site.yml` is on the top-level. I run the playbook also from the top-level directory. As I don't want too many random files in the top-level, I stored the YAML file for configuring wildfly somewhere in the directory structure:

```
.
├── site.yml
├── hosts.yml
├── files
│   └── wildfly
│       └── custom_wildfly_config.yml
```

And in the playbook:

```
---
- hosts: wildfly
[...]
  - name: Configure Wildfly with wildfly_systemd
    include_role:
      name: wildfly_systemd
    vars:
      wildfly_version: '26.0.1.Final'
      wildfly_install_workdir: '/opt/'
      wildfly_config_base: 'standalone-full-ha.xml'
      wildfly_enable_yml_config: 'yes'
      wildfly_yml_configs: ["files/wildfly/custom_wildfly_config.yml"]
[...]
```

Running the playbook results in an error:

```
ansible-playbook -i hosts site.yml
[...]

TASK [middleware_automation.wildfly.wildfly_systemd : Deploy YAML configuration files] ****************************************************************************************************************************
failed: [wildfly] (item=files/wildfly/custom_wildfly_config.yml) => {"ansible_loop_var": "file", "changed": false, "checksum": "573af281b58a5d55468dd668d77b9144c52b9559","file": "files/wildfly/custom_wildfly_config.yml",
"msg": "Destination directory /opt/wildfly-26.0.1.Final/standalone/files/wildfly does not exist"}
```

The task copies the YAML file to the managed node and expects that this directory structure below `/opt/wildfly-26.0.1.Final/standalone` already exists?

I 'solved' the problem by moving the YAML file to the top-level.

My question is: Do I do something wrong or is this intended? Actually I don't care where exactly the file on the managed node is stored, but I would like to have some kind of freedom where I store the file on my controller.
