### ISSUE TITLE
wildfly_home/eap_home variable does not cause installation to be placed in specified directory

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#145]
##### SUMMARY
When setting the `eap_home` value for the `eap_install` role, regardless of the value set it will still be installed in `/opt/jboss_eap/jboss-eap-<version>`

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION
```
ansible [core 2.14.2]
  config file = /home/consultant/57734-ansible-jboss/ansible.cfg
  configured module search path = ['/home/consultant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/consultant/.ansible/collections/ansible_collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection             Version
---------------------- -------
ansible.posix          1.5.4  
community.general      7.1.0  
redhat.eap             1.3.4  
redhat.runtimes_common 1.1.2  
```

##### STEPS TO REPRODUCE

```yaml
- name: Install the required packages for JBoss
  ansible.builtin.package:
    name:
      - java-11-openjdk-headless
      - java-11-openjdk-devel
      - java-1.8.0-openjdk

- name: Install JBoss from Red Hat Customer Portal
  include_role:
    name: redhat.eap.eap_install
  vars:
    eap_enable_yml_config: True
    eap_offline_install: False
    eap_apply_cp: True
    # Define the variables to be used in the eap_yml_configs (variable within the role) templates
    # eap_caches:
    #  - { name: 'cache1', default: 'default', aliases: 'alias_cache1', modules: 'org.wildfly.clustering.server' }
    #  - { name: 'cache2', default: 'default', aliases: 'alias_cache2', modules: 'org.wildfly.clustering.server' }
    # List the template (i.e. logging, infinispan caches, datasources+drivers) to be used
    eap_yml_configs:
      - datasources-config.yml.j2
      - infinispan-caches-config.yml.j2
      - logging-config.yml.j2

```

##### EXPECTED RESULTS
With the `eap_home` set to `/apps`, I expected that the JBoss installation would be directly inside of the `/apps` directory

##### ACTUAL RESULTS
JBoss EAP was installed under `/opt/jboss_eap/jboss-eap-7.4.12`
