### ISSUE TITLE
eap_user/eap_group is not completely setting permissions correctly

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#146]
##### SUMMARY
Setting the `eap_user` and `eap_group` is not consistently setting ownership and service user on the install and systemd roles.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/consultant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/consultant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.11.2 (main, Feb 16 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```
Collection             Version
---------------------- -------
ansible.posix          1.5.4  
community.general      7.1.0  
redhat.eap             1.3.4  
redhat.runtimes_common 1.1.2  
```

##### STEPS TO REPRODUCE

```yaml
- name: Install JBoss from Red Hat Customer Portal
  include_role:
    name: redhat.eap.eap_install
  vars:
    eap_enable_yml_config: True
    eap_offline_install: False
    eap_apply_cp: True
    # Define the variables to be used in the eap_yml_configs (variable within the role) templates
    # eap_caches:
    #  - { name: 'cache1', default: 'default', aliases: 'alias_cache1', modules: 'org.wildfly.clustering.server' }
    #  - { name: 'cache2', default: 'default', aliases: 'alias_cache2', modules: 'org.wildfly.clustering.server' }
    # List the template (i.e. logging, infinispan caches, datasources+drivers) to be used
    eap_yml_configs:
      - datasources-config.yml.j2
      - infinispan-caches-config.yml.j2
      - logging-config.yml.j2

- name: Install JBoss systemd service
  include_role:
    name: redhat.eap.eap_systemd

- name: Configure JBoss admin account
  command: "{{ eap_home }}/bin/add-user.sh -u {{ eap_admin_username }} -p {{ eap_admin_password }}"
  tags:
    - jboss-admin

- name: Validate JBoss installation
  include_role:
    name: redhat.eap.eap_validation
```

##### EXPECTED RESULTS
Expected that the JBoss EAP installation directories would be owned by the specified user/group

##### ACTUAL RESULTS
The JBoss EAP installation happens, but the specified user/group permissions are not used. Instead, the `eap` user and group are used. On the command-line for the `ansible-playbook` command we had set `eap_user=mware` and `eap_group=mware`. We also tried pre-creating the `mware` user and it did not resolve the issue.
```
drwxr-xr-x. 3 eap eap     27 Jun 23  2021 appclient
-rw-r-----. 1 eap eap     13 Sep 21 15:04 .applied_patch_checksum_bbd3cb6f23e07550d3571c6dfa53c21a4b00b6e5.txt
drwxr-xr-x. 4 eap eap   4096 Sep 21 15:04 bin
drwxr-xr-x. 5 eap eap     52 Jun 23  2021 docs
drwxr-xr-x. 4 eap eap     38 Jun 23  2021 domain
drwxr-xr-x. 4 eap eap     57 Sep 21 15:04 .installation
-rw-r--r--. 1 eap eap    419 Jun 23  2021 JBossEULA.txt
-rw-r--r--. 1 eap eap 495495 Sep 21 15:04 jboss-modules.jar
-rw-r-----. 1 eap eap      6 Sep 21 15:04 .latest_applied_patch.txt
-rw-r--r--. 1 eap eap  26530 Jun 23  2021 LICENSE.txt
drwxr-xr-x. 3 eap eap     44 Jun 23  2021 migration
drwxr-xr-x. 3 eap eap     20 Jun 23  2021 modules
drwxr-xr-x. 8 eap eap    106 Sep 21 15:06 standalone
-rw-r--r--. 1 eap eap     66 Sep 21 15:04 version.txt
drwxr-xr-x. 4 eap eap    158 Jun 23  2021 welcome-content
drwxr-xr-x. 3 eap eap     28 Jun 23  2021 .well-known
```
