### ISSUE TITLE
Firewalld role is insufficient to allow cluster node discovery via JGroups

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#151]
##### SUMMARY
In order to get JGroups UDP_MPING discovery working I had to add additional firewalld rules

##### ISSUE TYPE
 - Feature Request

##### ANSIBLE VERSION

```
ansible-playbook [core 2.14.2]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/consultant/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/consultant/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.2 (main, Feb 16 2023, 00:00:00) [GCC 11.3.1 20221121 (Red Hat 11.3.1-4)] (/usr/bin/python3.11)
  jinja version = 3.1.2
  libyaml = True
```

##### COLLECTION VERSION

```

# /usr/share/ansible/collections/ansible_collections
Collection               Version
------------------------ -------
redhat.rhel_mgmt         1.1.0  
redhat.rhel_system_roles 1.21.1 

# /home/consultant/.ansible/collections/ansible_collections
Collection             Version
---------------------- -------
ansible.posix          1.5.4  
community.general      7.1.0  
redhat.eap             1.4.3  
redhat.runtimes_common 1.1.3  
```

##### STEPS TO REPRODUCE

```yaml
- name: Install JBoss firewalld rules
  include_role:
    name: redhat.eap.eap_firewalld
  tags:
    - jboss_firewall
```

Vars:
```
eap_listen_ports:
  - 8009
  - 8080
  - 8443
  - 4712
  - 4713
  - 7600
```

##### EXPECTED RESULTS

I had to add the following to my tasks:

```
- name: Allow Multicast packets for cluster discovery
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop:
    - rule family="ipv4" source address="230.0.0.4" protocol value="ip" accept
    - rule family="ipv4" destination address="230.0.0.4" protocol value="ip" accept
  tags:
    - jboss_firewall

- name: Allow JGroups ports
  ansible.posix.firewalld:
    zone: internal
    port: "{{ item }}"
    state: enabled
    permanent: true
    immediate: true
  loop:
    - "7600/udp"
    - "7800/udp"
    - "7600/tcp"
    - "7800/tcp"
    - "45688/udp"
  tags:
    - jboss_firewall
````

##### ACTUAL RESULTS
The firewall role does set the desired ports, but it does not allow the multicast packets for the multicast IP needed for JBoss.

Based on the (possibly default) value of `eap_multicast_addr`, the rich rules above are needed and possibly the individual ports and protocols listed below them.
