### ISSUE TITLE
eap_driver role not working

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#152]
##### SUMMARY
When we configured the playbook to use the eap_driver role to install an Oracle JDBC driver module it did not do anything

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
ansible-playbook [core 2.14.10]
  config file = /home/dphillips/.ansible.cfg
  configured module search path = ['/home/dphillips/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.11/site-packages/ansible
  ansible collection location = /home/dphillips/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.11.5 (main, Aug 28 2023, 00:00:00) [GCC 12.3.1 20230508 (Red Hat 12.3.1-1)] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION

```
# /home/dphillips/.ansible/collections/ansible_collections
Collection                                Version
----------------------------------------- -------
ansible.posix                             1.5.4  
community.general                         6.2.0  
kubernetes.core                           2.4.0  
middleware_automation.common              1.1.0  
middleware_automation.infinispan          1.1.4  
middleware_automation.keycloak            1.1.0  
middleware_automation.redhat_csp_download 1.2.2  
middleware_automation.wildfly             1.3.4  
redhat.data_grid                          1.1.3  
redhat.eap                                1.3.4  
redhat.runtimes_common                    1.1.0  
```

##### STEPS TO REPRODUCE

```yaml
- name: Install Oracle JDBC Driver Module
  include_role:
    name: redhat.eap.eap_driver
  vars:
    eap_driver_module_name: "com.oracle.ojdbc8"
    eap_driver_jar_filename: "ojdbc8.jar"
    eap_driver_version: "8.1920"
    eap_driver_jar_url: "https://download.oracle.com/otn-pub/otn_software/jdbc/1920/ojdbc8.jar"
```

##### EXPECTED RESULTS

Expected that the module directory, module.xml file, and the ojdbc8.jar file would be added to the ${JBOSS_HOME}/modules directory

##### ACTUAL RESULTS

No effect whatsoever... Strangely, even though we did not request a PostgreSQL driver the Ansible output shows that it's creating one. Even though there is output saying that it created the PostgreSQL driver module, it did not create that module either!!
