### ISSUE TITLE
eap_firewalld should allow multicast traffic and UDP ports

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#156]
##### SUMMARY

In order to establish a JGroups cluster using the default UDP_MPING, multicast addresses and UDP ports need to be allowed
by firewalld.

I needed to add the following to my playbook in order for a cluster to form:

```
# To enable cluster node discovery using multicast UDP, set some rich rules for firewalld to enable source/destination
# for the multicast IP. The `eap_multicast_addr` can be set in the `group_vars`
- name: Allow Multicast packets for cluster discovery
  ansible.posix.firewalld:
    rich_rule: "{{ item }}"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop:
    - rule family="ipv4" source address="{{ eap_multicast_addr | default('230.0.0.4') }}" protocol value="ip" accept
    - rule family="ipv4" destination address="{{ eap_multicast_addr | default('230.0.0.4') }}" protocol value="ip" accept
  tags:
    - jboss_firewall

- name: Allow UDP ports for clustering
  ansible.posix.firewalld:
    port: "{{ item }}/udp"
    zone: internal
    permanent: true
    immediate: true
    state: enabled
  loop:
    - 8009
    - 8080
    - 10080
    - 8443
    - 4712
    - 4713
    - 7600
    - 7800
    - 45688
    - 55200
    - 54200
  tags:
    - jboss_firewall
```

##### ISSUE TYPE
 - Feature Idea
