### ISSUE TITLE
wildfly_install - failure when wildfly_archive_dir defined

### ISSUE THREAD

**Issue by aushacker** [ansible-middleware/wildfly#16]
Was able to successfully install several versions of Wildfly. Found that /opt/wildfly was getting a little cluttered up with .zip files so I thought I'd add a custom archive dir:

```
---
- name: "Wildfly installation and configuration"
  hosts:
    - buff
  become: yes
  vars:
    wildfly_version: '26.0.1.Final'
    wildfly_archive_dir: '{{ wildfly_install_workdir }}/archive'
  collections:
    - middleware_automation.wildfly
  roles:
    - wildfly_install
```

Defining `wildfly_archive_dir` caused the script to fail with:
```
TASK [middleware_automation.wildfly.wildfly_install : include_tasks] ***************************************
included: /Users/XXX/.ansible/collections/ansible_collections/middleware_automation/wildfly/roles/wildfly_install/tasks/install/wildfly.yml for buff

TASK [middleware_automation.wildfly.wildfly_install : assert] **********************************************
ok: [buff]

TASK [middleware_automation.wildfly.wildfly_install : Download Wildfly zipfile from {{ wildfly_install.download_url }} into {{ wildfly_install.path_to_archive }}] ***
ok: [buff -> localhost]

TASK [middleware_automation.wildfly.wildfly_install : include_tasks] ***************************************
skipping: [buff]

TASK [middleware_automation.wildfly.wildfly_install : include_tasks] ***************************************
skipping: [buff]

TASK [middleware_automation.wildfly.wildfly_install : Copy archive to target nodes] ************************
fatal: [buff]: FAILED! => {"changed": false, "checksum": "1f6676a7372256d5e2e80e5372b611a0e089a728", "msg": "Destination directory /opt/wildfly//archive does not exist"}
```

Have had a look at the script but don't understand it well enough to mess with it. Any suggestions?

**Comment by rpelisse** [comment]
@aushacker it seems that you just need to ensure the directory is created:
```
- name:
  file:
    status: directory
    path: "{{ wildfly_install_workdir }}/archive"
```
That should do the trick as far as I can see.

Note that you should probably defined a variable for this path, add it to the role's vars/main.yml and provide a default value in the role's defaults/main.yml.
