### ISSUE TITLE
Set selinux file context for custom installation location

### ISSUE THREAD

**Issue by InfoSec812** [ansible-middleware/wildfly#163]
##### SUMMARY
When using a custom installation location (at least), the file context(s) of the jboss installation are not correct to allow for systemd to start the service

I needed to add the following to my playbook to overcome this issue:

```
- name: Set SELinux context for JBoss dir
  community.general.sefcontext:
    target: '{{ eap_install_workdir | regex_replace("/$", "") }}(/.*)?'
    setype: init_exec_t
    state: present
  tags:
    - selinux

- name: Reset SELinux context for JBoss dir
  ansible.builtin.command:
    cmd: 'restorecon -R -v "{{ eap_install_workdir | regex_replace("/$", "") }}"'
  changed_when: true
  tags:
    - selinux
```

##### ISSUE TYPE
 - Feature Idea
