### ISSUE TITLE
Set apply_cp to False does not work with the downstream collection

### ISSUE THREAD

**Issue by rpelisse** [ansible-middleware/wildfly#185]
##### SUMMARY
Set apply_cp to False does not work with the downstream collection, the playbook still retrieve the patch version from the API and try to download and apply the patch.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```
# ansible-playbook --version
ansible-playbook [core 2.15.9]
  config file = /work/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.9/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible-playbook
  python version = 3.9.18 (main, Jan  4 2024, 00:00:00) [GCC 11.4.1 20230605 (Red Hat 11.4.1-2)] (/usr/bin/python3)
  jinja version = 3.1.2
  libyaml = True

```

##### COLLECTION VERSION

```
Collection             Version
---------------------- -------
ansible.posix          1.5.4  
redhat.eap             1.5.0  
redhat.runtimes_common 1.1.3  
```

##### STEPS TO REPRODUCE

```bash
ansible-playbook -i inventory -e @service_account.yml redhat.eap.playbook -e eap_apply_cp=False
```

**Comment by rpelisse** [comment]
OK, it seems it's more a default of the [ansible-playbook command](https://github.com/ansible/ansible/issues/17193#issuecomment-281483618). 

To fix it anyway, I'll add force a conversion to boolean:
```
name: "Apply latest cumulative patch"
  ansible.builtin.include_role:
    name: eap_utils
    tasks_from: apply_cp.yml
  when:
    - eap_apply_cp is defined and (eap_apply_cp | bool )
    - eap_enable is defined and (eap_enable | bool )
```
