### ISSUE TITLE
Align wildfly_uninstall defaults to the rest of the defaults

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#196]
##### SUMMARY
I would expect
```
  roles:
    - role: wildfly_install
    - role: wildfly_systemd
    - role: wildfly_uninstall
```
to work smoothly, but I am getting
```
fatal: [instance]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'eap_uninstall_service_name' is undefined. 'eap_uninstall_service_name' is undefined. 'eap_uninstall_service_name' is undefined. 'eap_uninstall_service_name' is undefined"}
```
Note it is from the downstram.

Rest of the roles defaults are aligned, IMO uninstall shouldn't be an exception.
