### ISSUE TITLE
systemd role works wrong when setting up multiple instances

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#201]
##### SUMMARY
I am working with the downstream, but I guess it works same (wrongly) with the upstream.

I have following converge.yml in the molecule testing framework:
```
---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  collections:
    - redhat.eap
  roles:
    - role: eap_install
    - role: eap_systemd
  tasks:
      - name: "Set up for WildFly instance {{ item }}"
        include_role:
          name: eap_systemd
        vars:
          eap_node_id: "eap-{{ item }}"
          eap_instance_name: "eap-{{ item }}"
          eap_service_name: "eap-{{ item }}-service"
          eap_config_base: standalone-ha.xml
          eap_basedir_prefix: "/opt/eap-{{ item }}"
          eap_port_range_offset: "{{ item * 100 }}"
        loop: "{{ range(0,3) | list }}"
      - name: ok
```

The role install 4 services (in the container):

```
$ systemctl
...
eap-0-service.service                  loaded failed failed    JBoss EAP (standalone mode)                          
eap-1-service.service                  loaded active running   JBoss EAP (standalone mode)                          
eap-2-service.service                  loaded active running   JBoss EAP (standalone mode)                          
eap.service                            loaded active running   JBoss EAP (standalone mode) 
```

eap-x have the right base location (`/opt/eap-x`), however eap.service is run in the default one (`/opt/jboss_eap/...`). 

Running pocesses:
```
eap          726  0.0  0.0  17100  2944 ?        Ss   14:55   0:00 /bin/sh /opt/jboss_eap/jboss-eap-7.4/bin/standalone.sh -c eap.xml -b 0.0.0.0 -bmanagement 127.0.0.1 -Djboss.bind.address.private=127.0.0.1 -Djboss.default.multicast.address=230.0.0.4 -Djboss.server.config.dir=/opt/jboss_eap/jboss-eap-7.4//standalone/configuration/ -Djboss.server.base.dir=/opt/jboss_eap/jboss-eap-7.4//standalone -Djboss.tx.node.id=instance -Djboss.node.name=eap -Djboss.socket.binding.port-offset=0 -Dwildfly.statistics-enabled=false

eap         1823  0.0  0.0  17100  2944 ?        Ss   14:56   0:00 /bin/sh /opt/jboss_eap/jboss-eap-7.4/bin/standalone.sh -c eap-1.xml -b 0.0.0.0 -bmanagement 127.0.0.1 -Djboss.bind.address.private=127.0.0.1 -Djboss.default.multicast.address=230.0.0.4 -Djboss.server.config.dir=/opt/jboss_eap/jboss-eap-7.4//standalone/configuration/ -Djboss.server.base.dir=/opt/eap-1/standalone -Djboss.tx.node.id=eap-1 -Djboss.node.name=eap-1 -Djboss.socket.binding.port-offset=100 -Dwildfly.statistics-enabled=false

eap         2374  0.0  0.0  17100  2944 ?        Ss   14:56   0:00 /bin/sh /opt/jboss_eap/jboss-eap-7.4/bin/standalone.sh -c eap-2.xml -b 0.0.0.0 -bmanagement 127.0.0.1 -Djboss.bind.address.private=127.0.0.1 -Djboss.default.multicast.address=230.0.0.4 -Djboss.server.config.dir=/opt/jboss_eap/jboss-eap-7.4//standalone/configuration/ -Djboss.server.base.dir=/opt/eap-2/standalone -Djboss.tx.node.id=eap-2 -Djboss.node.name=eap-2 -Djboss.socket.binding.port-offset=200 -Dwildfly.statistics-enabled=false
```
Notice `-Djboss.tx.node.id=instance -Djboss.node.name=eap`

**Comment by guidograzioli** [comment]
You likely had an eap from a former deployment, since the three eap should be eap-0 eap-1 and eap-2 not [eap,eap-1,eap-2]

however, in general, do NOT do this pls:

```yaml
 vars_files:
    - vars.yml
  [..]
  roles:
    - role: eap_install
    - role: eap_systemd
  tasks:
      - name: "Set up for WildFly instance {{ item }}"
        include_role:
          name: eap_systemd
        vars:
          eap_node_id: "eap-{{ item }}"
```

since the precedence between the loaded var file and the vars passed to the role can give nasty surprises.

Choose one or the other or in any case make sure there are no overlappings.

Ah final note, it seems you have systemd running twice, first here:

```
  roles:
    - role: eap_install
    - role: eap_systemd```
   
and the second with include_role:

```
        include_role:
          name: eap_systemd
```
