### ISSUE TITLE
Systemd not setting the log dir when used in the pool

### ISSUE THREAD

**Issue by istraka** [ansible-middleware/wildfly#208]
##### SUMMARY
Using systemd role to setup multiple instances results into all instances logging into the same file:

```

  collections:
    - redhat.eap
  roles:
    - role: eap_install
  tasks:
    - name: "Set up for WildFly instance {{ item }}"
      include_role:
        name: eap_systemd
      vars:
        eap_node_id: "eap-{{ item }}"
        eap_instance_name: "eap-{{ item }}"
        eap_service_name: "eap-{{ item }}-service"
        eap_config_base: standalone-full-ha.xml
        eap_basedir_prefix: "/opt/eap-{{ item }}"
        eap_port_range_offset: "{{ item * 100 }}"
        eap_enable_yml_config: True
        eap_java_opts: '-Xmx1024M -Xms512M -Djboss.server.log.dir=/opt/eap-{{ item }}/standalone/log/'
```

I need to setup `-Djboss.server.log.dir=/opt/eap-{{ item }}/standalone/log/` explicitly, which should be set by systemd role like. E.g. `org.jboss.boot.log.file` is set up right.

**Comment by guidograzioli** [comment]
Can you try with:

```yaml
eap_basedir_prefix: "/opt/eap-{{ item }}"
```

you need:

```yaml
wildfly_install_workdir: "/opt/eap-{{ item }}"
```

**Comment by istraka** [comment]
I get "file not found: /opt/eap-0/eap-7.4/.latest_applied_patch.txt" with both solutions.

**Comment by guidograzioli** [comment]
Can you post the name of tasks that fails from the log and your complete playbook? I do not understand the playbook above with wildfly_install out of the loop and wildfly_systemd in it (the vars for wildfly_systemd won't be visible to wildfly_install like that)

**Comment by guidograzioli** [comment]
Meanwhile I think I found where the file not found comes from, the PR above addresses it

**Comment by istraka** [comment]
```
TASK [redhat.eap.eap_systemd : Check current EAP patch installed] **************
fatal: [instance]: FAILED! => {"changed": false, "msg": "file not found: /opt/eap-0/eap-7.4/.latest_applied_patch.txt"}
```

**Comment by istraka** [comment]
The scenario comes from https://github.com/ansible-middleware/wildfly/tree/main/roles/wildfly_systemd.

The playbook (molecule converge):
```
---
- name: Converge
  hosts: all
  vars_files:
    - vars.yml
  collections:
    - redhat.eap
  roles:
    - role: eap_install
  tasks:
    - name: "Set up for WildFly instance {{ item }}"
      include_role:
        name: eap_systemd
      vars:
        eap_node_id: "eap-{{ item }}"
        eap_instance_name: "eap-{{ item }}"
        eap_service_name: "eap-{{ item }}-service"
        eap_config_base: standalone-full-ha.xml
        eap_basedir_prefix: "/opt/eap-{{ item }}"
        eap_home: "{{ eap_basedir_prefix }}/eap-7.4"
        eap_port_range_offset: "{{ item * 100 }}"
        eap_enable_yml_config: True
        eap_java_opts: '-Xmx1024M -Xms512M -Djboss.server.log.dir=/opt/eap-{{ item }}/standalone/log/'
        eap_yml_configs:
          - configure_tcp_ping.yml
      loop: "{{ range(0,3) | list }}"
    - ansible.builtin.pause:
        prompt: "Enter a secret"
        echo: no 
```

vars.yml:
```
eap_validation_debug: True
eap_qe_pre_ga_testing: True
eap_offline_install: True
eap_patch_version: 7.4.15
assets_server: http://download.eng.brq.redhat.com/released/JBoss-middleware
eap_dot_assets:
  - /eap7/7.4.0/jboss-eap-7.4.0.zip
eap_pre_ga_patch_url: file:///home/istraka/delete/eap74-jdk17/jboss-eap-7.4.15-patch.zip
```

7.4.0 zip and 7.4.15 patch are pre downloaded.

The reason why the install role is not in the loop is to save the space. A user can run multiple WildFly instances having just one installation to save space.
