### ISSUE TITLE
vars could be moved to default

### ISSUE THREAD

**Issue by gh-msvefors** [ansible-middleware/wildfly#38]
##### SUMMARY

the `vars/main.yml` contain the variables for the role, if the file was located in `defaults/main.yml` it could be overridden in a playbook.

##### ISSUE TYPE
 - Bug Report

##### ANSIBLE VERSION

```

```

##### COLLECTION VERSION

```

```

##### STEPS TO REPRODUCE

```yaml
---
- hosts: localhost

  gather_facts: true
  roles:
    - role: wildfly_driver
      vars:
        jdbc_driver_module_dir: "{{ wfly_home }}/modules/system/layers/base/com/oracle/main"
        jdbc_driver_module_name: "com.oracle"
        jdbc_driver_jar_installation_path: "{{ jdbc_driver_module_dir }}/{{ jdbc_driver_jar_filename }}"
        jdbc_driver_jar_filename: "ojdbc8-21.1.0.0.jar"
        #        jdbc_driver_version: "21.1.0.0"
        jdbc_driver_jar_url: "https://repo1.maven.org/maven2/com/oracle/database/jdbc/ojdbc8/21.1.0.0/ojdbc8-21.1.0.0.jar"
```

##### EXPECTED RESULTS

I expect it to be able to create directory

##### ACTUAL RESULTS

```
#    - name: "Ensures Postgres  JDBC Driver is present: "
fatal: [localhost]: FAILED! => {"changed": false, "msg": "There was an issue creating  as requested: 'NoneType' object has no attribute 'strip'", "path": null}
```
